# Generated by Django 3.1.1 on 2021-09-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_auto_20210913_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='blurb',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
