# Generated by Django 3.1.1 on 2021-09-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='image',
        ),
        migrations.AddField(
            model_name='hero',
            name='url_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
